### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by Amritanshu02** [avinash201199/HTML-Sign-In-Form#3]
There should be a sign up option also

**Comment by Amritanshu02** [comment]
Hello,I would like to work on this issue , could you assign it to me

**Comment by Abhishek07-0302** [comment]
Hey, I would like to work on this. Kindly assign me if available.

**Comment by avinash201199** [comment]
> Hey, I would like to work on this. Kindly assign me if available.

create your own issue will assign you

**Comment by Abhishek07-0302** [comment]
There should be a Contact us feedback type form to raise a query.

**Comment by Amritanshu02** [comment]
Thank you Sir. The issue had been resolved.
